// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Build orchestration: scaffold crates, then invoke the per-target toolchain
//! (`maturin` for Python) and collect artifacts into the output directory.

use std::fs;
use std::path::Path;
use std::process::Command;

use crate::config::{Manifest, Source};
use crate::error::{Error, Result};
use crate::paths::absolute;
use crate::scaffold;

/// A codegen artifact target. Phase A implements `python`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Target {
    /// pip-installable Python wheel (PyO3 + maturin).
    Python,
}

/// Parse a single target name.
pub fn parse_target(s: &str) -> Result<Target> {
    match s.trim() {
        "python" => Ok(Target::Python),
        "cxx" | "rust" => Err(Error::UnsupportedTarget(s.trim().to_string())),
        other => Err(Error::Config(format!(
            "unknown target `{other}` (expected `python`)"
        ))),
    }
}

/// Parse a comma-separated target list.
pub fn parse_targets(spec: &str) -> Result<Vec<Target>> {
    spec.split(',')
        .filter(|s| !s.trim().is_empty())
        .map(parse_target)
        .collect()
}

/// Targets present in the manifest (used when `--targets` is omitted).
pub fn default_targets(manifest: &Manifest) -> Vec<Target> {
    let mut targets = Vec::new();
    if manifest.python.is_some() {
        targets.push(Target::Python);
    }
    targets
}

/// Marker file written into every directory this tool creates, so deletion can
/// verify ownership before removing anything.
const MARKER: &str = ".quent-codegen";

/// Create `dir` and drop an ownership marker so [`owned_remove`] may later wipe it.
fn create_owned(dir: &Path) -> Result<()> {
    fs::create_dir_all(dir).map_err(|source| Error::Io {
        path: dir.to_path_buf(),
        source,
    })?;
    let marker = dir.join(MARKER);
    fs::write(&marker, "generated by quent-codegen; safe to delete\n").map_err(|source| Error::Io {
        path: marker,
        source,
    })
}

/// Recursively remove `dir` only if this tool created it (has [`MARKER`]).
/// A missing directory is a no-op; an unmarked directory is refused so a
/// user-supplied `--scaffold-dir`/`--out` cannot delete unrelated files.
fn owned_remove(dir: &Path) -> Result<()> {
    if !dir.exists() {
        return Ok(());
    }
    if dir.join(MARKER).is_file() {
        fs::remove_dir_all(dir).map_err(|source| Error::Io {
            path: dir.to_path_buf(),
            source,
        })
    } else {
        Err(Error::Config(format!(
            "refusing to delete `{}`: not created by quent-codegen (missing `{MARKER}` marker); \
             remove it manually or choose another directory",
            dir.display()
        )))
    }
}

/// Wipe the scaffold directory and (re)generate crates for `targets`.
/// `quent` is the dependency source injected into generated crates (from the
/// manifest's `[quent]`, or a workflow override).
pub fn scaffold_only(
    manifest: &Manifest,
    manifest_dir: &Path,
    quent: &Source,
    targets: &[Target],
    scaffold_dir: &Path,
) -> Result<()> {
    if targets.is_empty() {
        return Err(Error::Config(
            "no targets selected; add a [python] table or pass --targets".into(),
        ));
    }
    owned_remove(scaffold_dir)?;
    create_owned(scaffold_dir)?;
    for target in targets {
        match target {
            Target::Python => {
                scaffold::scaffold_python(manifest, manifest_dir, quent, scaffold_dir)?;
            }
        }
    }
    Ok(())
}

/// Scaffold, then build and package each target into `out`.
pub fn build(
    manifest: &Manifest,
    manifest_dir: &Path,
    quent: &Source,
    targets: &[Target],
    out: &Path,
    scaffold_dir: &Path,
    release: bool,
) -> Result<()> {
    scaffold_only(manifest, manifest_dir, quent, targets, scaffold_dir)?;
    for target in targets {
        match target {
            Target::Python => {
                let project = scaffold_dir.join("python");
                let out_python = absolute(&out.join("python"));
                run_maturin(&project, &out_python, release)?;
                eprintln!("built Python wheel(s) into {}", out_python.display());
            }
        }
    }
    Ok(())
}

fn run_maturin(project: &Path, out: &Path, release: bool) -> Result<()> {
    // Refuse to adopt an unmarked existing dir (e.g. a user `./python` source)
    // and clear any prior wheels so stale artifacts can't contaminate the upload.
    owned_remove(out)?;
    create_owned(out)?;
    let mut cmd = Command::new("maturin");
    cmd.arg("build");
    if release {
        cmd.arg("--release");
    }
    cmd.arg("--out").arg(out);
    cmd.current_dir(project);
    eprintln!("running `maturin build` in {}", project.display());
    let status = cmd.status().map_err(|source| Error::Spawn {
        program: "maturin".into(),
        source,
    })?;
    if !status.success() {
        return Err(Error::Command {
            program: "maturin".into(),
            status,
        });
    }
    Ok(())
}

/// Remove the scaffold directory and CLI-created artifact subdirectories.
/// Only directories bearing the ownership marker are deleted.
pub fn clean(out: &Path, scaffold_dir: &Path) -> Result<()> {
    owned_remove(scaffold_dir)?;
    for sub in ["python", "cxx", "rust"] {
        owned_remove(&out.join(sub))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn owned_remove_refuses_unmarked_dir() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("user_data");
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("keep.txt"), "important").unwrap();
        assert!(owned_remove(&dir).is_err());
        assert!(
            dir.join("keep.txt").exists(),
            "must not delete unmarked dir"
        );
    }

    #[test]
    fn owned_remove_deletes_marked_dir() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("scaffold");
        create_owned(&dir).unwrap();
        owned_remove(&dir).unwrap();
        assert!(!dir.exists());
    }

    #[test]
    fn owned_remove_missing_is_ok() {
        let tmp = tempfile::tempdir().unwrap();
        owned_remove(&tmp.path().join("nope")).unwrap();
    }
}
