// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Source templates for generated scaffold crates.
//!
//! Placeholders use the `__TOKEN__` form and are substituted via [`fill`].
//! Each generated `Cargo.toml` carries an explicit empty `[workspace]` table so
//! cargo treats it as its own workspace root and does not attach it to (or get
//! captured by) an ancestor workspace.

/// Replace every `(token, value)` pair in `template` (all occurrences).
pub fn fill(template: &str, pairs: &[(&str, &str)]) -> String {
    let mut out = template.to_string();
    for (token, value) in pairs {
        out = out.replace(token, value);
    }
    out
}

/// Generated instrumentation wrapper crate manifest.
pub const INSTR_CARGO: &str = r#"# Generated by quent-codegen — do not edit.
[workspace]

[package]
name = "__INSTR_PKG__"
version = "0.0.0"
edition = "2024"
publish = false

[features]
collector = ["quent-model/collector"]

[dependencies]
quent-model = { __QUENT_MODEL_DEP__ }
__MODEL_PKG__ = { __MODEL_DEP__ }
"#;

/// Generated instrumentation wrapper `lib.rs`.
pub const INSTR_LIB: &str = r#"// Generated by quent-codegen — do not edit.
pub use __MODEL_LIB__::*;
quent_model::instrumentation!(__MODEL_NAME__);
"#;

/// Generated PyO3 bridge crate manifest.
pub const PY_CARGO: &str = r#"# Generated by quent-codegen — do not edit.
[workspace]

[package]
name = "__PY_PKG__"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
name = "__MODULE__"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["abi3-py311"] }
__INSTR_PKG__ = { path = "../instrumentation" }

[build-dependencies]
quent-codegen = { __QUENT_CODEGEN_DEP__ }
__INSTR_PKG__ = { path = "../instrumentation" }
"#;

/// Generated PyO3 bridge `build.rs`.
pub const PY_BUILD: &str = r#"// Generated by quent-codegen — do not edit.
use quent_codegen::PyO3Options;

fn main() {
    let builder = __INSTR_LIB__::__MODEL_TYPE__::build("__MODEL_NAME__");

    let options = PyO3Options {
        module_name: "__MODULE__".into(),
        instrumentation_crate: "__INSTR_LIB__".into(),
    };

    let files = quent_codegen::emit_pyo3(&builder, &options);
    quent_codegen::write_pyo3_files(&files);

    let stub_files = quent_codegen::emit_pyo3_stubs(&builder, &options);
    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap());
    quent_codegen::write_generated_files(&stub_files, out_dir);
}
"#;

/// Generated PyO3 bridge `lib.rs` (includes the generated bridge from OUT_DIR).
pub const PY_LIB: &str = r#"// Generated by quent-codegen — do not edit.
include!(concat!(env!("OUT_DIR"), "/pyo3_bridge.rs"));
"#;

/// Generated `pyproject.toml` for the PyO3 bridge (maturin backend).
pub const PYPROJECT: &str = r#"# Generated by quent-codegen — do not edit.
[build-system]
requires = ["maturin>=1.10,<2"]
build-backend = "maturin"

[project]
name = "__DIST__"
version = "__VERSION__"
# The bridge is built with pyo3 `abi3-py311`, so one wheel covers Python >= 3.11.
requires-python = ">=3.11"

[tool.maturin]
manifest-path = "Cargo.toml"
module-name = "__MODULE__"
include = [
  { path = "__MODULE__/__init__.pyi", from = "out-dir", to = "" },
  { path = "__MODULE__/py.typed", from = "out-dir", to = "" },
]
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fill_replaces_all_occurrences() {
        let out = fill(
            PY_CARGO,
            &[("__INSTR_PKG__", "foo-instr"), ("__MODULE__", "foo")],
        );
        assert_eq!(out.matches("foo-instr").count(), 2);
        assert!(out.contains("name = \"foo\""));
        // The empty workspace table must always be present.
        assert!(out.contains("[workspace]\n"));
    }
}
